# Generated by Django 4.2.3 on 2023-07-22 21:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('csf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), null=True, size=10),
        ),
    ]
