# Generated by Django 4.2.3 on 2023-07-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csf', '0002_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
