# Generated by Django 4.2.3 on 2023-10-29 18:49

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('csf', '0005_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec3',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), null=True, size=15),
        ),
    ]
