# Generated by Django 4.2.3 on 2023-11-01 21:06

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('csf', '0006_rename_desc_product_description_remove_product_spec1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='schematics',
            field=models.FileField(null=True, upload_to='schematics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default='no sizes provided', size=20),
        ),
    ]
