# Generated by Django 4.2.3 on 2023-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csf', '0007_product_schematics_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='schematics',
            field=models.FileField(blank=True, null=True, upload_to='schematics/'),
        ),
    ]
