# Generated by Django 4.2.3 on 2023-11-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csf', '0008_alter_product_schematics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='schematics',
        ),
        migrations.AddField(
            model_name='product',
            name='schematic',
            field=models.FileField(default='schematics/roomba-overlay.jpg', upload_to='schematics/'),
        ),
    ]
