# Generated by Django 4.2.3 on 2023-11-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csf', '0009_remove_product_schematics_product_schematic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
